baseurl = "https://jghoman.github.io/"
languageCode = "en"
title = "Jakob Homan's blog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/jghoman\">Jakob Homan</a> 2021"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Jakob Homan" # Author full name
authorEmail = "jghoman@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = false  # Load Disqus comments on click


[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "blueboxtraveler"
github = "jghoman"
linkedin = "jghoman"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","twitter","linkedin"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true