# The URL the site will be built for
base_url = "https://jghoman.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
 {name = "categories"},
 {name = "tags"},
]

theme = "dinkleberg"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
blog_title="Jakob Homan Occasionally Blogs"
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Relative Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"

og_image="https://user-images.githubusercontent.com/10289071/40806112-dd79ae78-64f6-11e8-8f24-63f387d5bb8f.jpg" # Image that will appear on social media
og_alt_image="Gotcha dinkleberg" # Alt for og_image
og_site_name="Jakob Homan Occasionally Blogs"
keywords="cinema, rust" # Keywords for SEO

copyright_year="2021" 


sidebar = [
    {name = "Social", urls=[
        {name="Twitter", url="https://twitter.com/BlueBoxTraveler"},

    ]}
]